# -*- coding: utf-8 -*-

"""
/***************************************************************************
 NormalizacionHoraria
                                 A QGIS plugin
 Normalización horaria
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-18
        copyright            : (C) 2022 by Manuel Vargas
        email                : mfvargas@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Manuel Vargas'
__date__ = '2022-09-18'
__copyright__ = '(C) 2022 by Manuel Vargas'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
import processing
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterNumber,                       
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterRasterDestination)



class NormalizacionHorariaAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    IMAGE_REFLECTANCE = 'IMAGE_REFLECTANCE'
    ZENITH = 'ZENITH'
    ZENITH_REFERENCE = 'ZENITH_REFERENCE'
    B1 = 'B1'
    B2 = 'B2'
    B3 = 'B3'
    B4 = 'B4'
    B5 = 'B5'
    B6 = 'B6'
    IMAGE_NORMALIZED = 'IMAGE_NORMALIZED'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.IMAGE_REFLECTANCE,
                self.tr('Imagen (pila) con valores de reflectancia')
            )
        )        

        self.addParameter(
            QgsProcessingParameterNumber(
                self.ZENITH, 
                self.tr('Cénit'),
                QgsProcessingParameterNumber.Double,
                41.51707124
            )
        )     

        self.addParameter(
            QgsProcessingParameterNumber(
                self.ZENITH_REFERENCE, 
                self.tr('Cénit de la imagen de referencia'),
                QgsProcessingParameterNumber.Double,
                36.9
            )
        )     

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.B1,
                self.tr("Banda 1 con valores de reflectancia")
            )
        ) 
        
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.B2,
                self.tr("Banda 2 con valores de reflectancia")
            )
        )     

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.B3,
                self.tr("Banda 3 con valores de reflectancia")
            )
        )                 
        
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.B4,
                self.tr("Banda 4 con valores de reflectancia")
            )
        )    

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.B5,
                self.tr("Banda 5 con valores de reflectancia")
            )
        )    

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.B6,
                self.tr("Banda 6 con valores de reflectancia")
            )
        )                 

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.IMAGE_NORMALIZED,
                self.tr("Imagen (pila) con normalización horaria")
            )
        )         


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieving parameters
        image_reflectance = self.parameterAsRasterLayer(parameters, self.IMAGE_REFLECTANCE, context)        
        zenith = parameters[self.ZENITH]
        zenith_reference = parameters[self.ZENITH_REFERENCE]        
        b1 = self.parameterAsOutputLayer(parameters, self.B1, context)
        b2 = self.parameterAsOutputLayer(parameters, self.B2, context)
        b3 = self.parameterAsOutputLayer(parameters, self.B3, context)
        b4 = self.parameterAsOutputLayer(parameters, self.B4, context)
        b5 = self.parameterAsOutputLayer(parameters, self.B5, context)
        b6 = self.parameterAsOutputLayer(parameters, self.B6, context)
        output = self.parameterAsOutputLayer(parameters, self.IMAGE_NORMALIZED, context)
        
        output1 = processing.run(
            "otb:BandMath", 
            {'il': image_reflectance, 
             'out': b1,
             'exp': "im1b1*(cos(" + str(zenith_reference)+ "*" + str(3.14159265359) + "/180)/cos(" + str(zenith)+ "*" + str(3.14159265359) + "/180))", 
             'outputpixeltype': 5}, 
            context=context, 
            feedback=feedback)
         
        output2 = processing.run(
            "otb:BandMath", 
            {'il': image_reflectance, 
             'out': b2,
             'exp': "im1b2*(cos(" + str(zenith_reference)+ "*" + str(3.14159265359) + "/180)/cos(" + str(zenith)+ "*" + str(3.14159265359) + "/180))", 
             'outputpixeltype': 5}, 
            context=context, 
            feedback=feedback)
            
        output3 = processing.run(
            "otb:BandMath", 
            {'il': image_reflectance, 
             'out': b3,
             'exp': "im1b3*(cos(" + str(zenith_reference)+ "*" + str(3.14159265359) + "/180)/cos(" + str(zenith)+ "*" + str(3.14159265359) + "/180))", 
             'outputpixeltype': 5}, 
            context=context, 
            feedback=feedback)
            
        output4 = processing.run(
            "otb:BandMath", 
            {'il': image_reflectance, 
             'out': b4,
             'exp': "im1b4*(cos(" + str(zenith_reference)+ "*" + str(3.14159265359) + "/180)/cos(" + str(zenith)+ "*" + str(3.14159265359) + "/180))", 
             'outputpixeltype': 5}, 
            context=context, 
            feedback=feedback)
            
        output5 = processing.run(
            "otb:BandMath", 
            {'il': image_reflectance, 
             'out': b5,
             'exp': "im1b5*(cos(" + str(zenith_reference)+ "*" + str(3.14159265359) + "/180)/cos(" + str(zenith)+ "*" + str(3.14159265359) + "/180))", 
             'outputpixeltype': 5}, 
            context=context, 
            feedback=feedback)
            
        output6 = processing.run(
            "otb:BandMath", 
            {'il': image_reflectance, 
             'out': b6,
             'exp': "im1b6*(cos(" + str(zenith_reference)+ "*" + str(3.14159265359) + "/180)/cos(" + str(zenith)+ "*" + str(3.14159265359) + "/180))", 
             'outputpixeltype': 5}, 
            context=context, 
            feedback=feedback)
            
        outputs = [output1['out'], output2['out'], output3['out'], output4['out'], output5['out'], output6['out']]
        
        image_normalized = processing.run(
            "gdal:merge", 
            {'INPUT': outputs,
             'OUTPUT': output,
             'DATA_TYPE' : 5,
             'SEPARATE' : True},
            context=context, 
            feedback=feedback)
        
        
        image_normalized = image_normalized['OUTPUT']
        
        return {self.IMAGE_NORMALIZED: image_normalized}


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Normalización horaria'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'REDD+ Costa Rica'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return NormalizacionHorariaAlgorithm()
